### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by Daniyyell** [daffainfo/Git-Secret#1]
**Anyone having save issues ?** 

**### Choose Branches:
2021/08/04 16:46:09 json: cannot unmarshal object into Go value of type main.Branch**

the tool does not give option to identify the branches as shown in the image.
But I would appreciate if you can give more usage example, thank you.

**Comment by daffainfo** [comment]
Maybe you have inputted the wrong repository.

And for example how to run this tool you can do this
```
./Git-Secret

____ _ ___    ____ ____ ____ ____ ____ ___ 
| __ |  |  __ [__  |___ |    |__/ |___  |  
|__] |  |     ___] |___ |___ |  \ |___  |  

Author: Muhammad Daffa
Version: 1.0                                                               

Input URL
https://github.com/daffainfo/Git-Secret (This is the repository)

Input path file contains dorks (Leave it blank if you don't have it)

Choose Branches:
(This is automatic showing branches in the repository you choose)

Starting....
[#] Checking: LICENSE
[#] Checking: README.md
.....
```

**Comment by Daniyyell** [comment]
Thank, 

 working perfectly
