### ISSUE TITLE
How can we add authentication to access Github Enterprise (https://github.company.com/) ?

### ISSUE THREAD

**Issue by dxjones** [daffainfo/Git-Secret#4]
Instead of searching public Github (https://github.com), ... I want to run this program to find secrets in a company's Github Enterprise (https://github.company.com) which requires **authentication**.

I think this can be done using a **github token**, but I don't know how to add this feature.

**Comment by daffainfo** [comment]
Hi @dxjones, yeah we don't have a feature to find some secret on GitHub enterprise like as you said. I think I can add some new features in the future
