### ISSUE TITLE
Support `go install`

### ISSUE THREAD

**Issue by hakbyte** [daffainfo/Git-Secret#5]
The documentation refers to `go get` but it's deprecated. `go install` should be used instead, for instance:

```
go install github.com/daffainfo/Git-Secret@latest
```
Which generates an error:

```
$ go install github.com/daffainfo/Git-Secret@latest
go: github.com/daffainfo/Git-Secret@latest (in github.com/daffainfo/Git-Secret@v0.0.0-20210805162334-e557be361004):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

Reference: https://go.dev/doc/go-get-install-deprecation

**Comment by hakbyte** [comment]
@daffainfo if you're interested I can create a pull request to fix this issue.

**Comment by daffainfo** [comment]
Hi, you can open a pull request to fix this, thank you :D

**Comment by hakbyte** [comment]
Hi, @daffainfo. I've just submitted a pull request. Please review it and let me know in case something is amiss.
